@startuml データ更新コントロールとホテルと予約
hide footbox
skinparam style strictuml
participant ":データ更新コントロール" as controller
participant ":ホテル" as hotel
participant ":予約" as yoyaku

activate controller
controller -> hotel: 予約 ()
activate hotel
hotel -> yoyaku: 生成 ()
hotel -> hotel: 予約登録（）
activate hotel
' deactivate hotel
deactivate hotel
deactivate controller
@enduml