@startuml 診察予約システム

[*] --> メニュー
メニュー -left-> [*]
メニュー --> 予約と確認 :予約と確認リンク
予約と確認 ---> メニュー :取り消しボタン
予約と確認 -right-> あなたの順番 :登録ボタン/確認ボタン
あなたの順番 --> メニュー :メニューボタン
メニュー -right-> 今の順番 :今の順番リンク
今の順番 -right-> メニュー :メニューボタン
@enduml